---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: httpapi  # put local.  We are processing against aws
  gather_facts: True  # don't gather facts against localhost
  collections:
  - check_point.mgmt.checkpoint

  tasks:

  - name: My task
    become: true

  - name: login to mgmt
    check_point_mgmt:
      command: login
      parameters:
        management: "192.168.176.200"
        username: "admin"
        password: "vpn123"
        fingerprint: "3E:FA:6E:DF:6E:94:87:8D:E9:31:9E:41:63:BD:7A:0B:1A:D7:7B:43:C2:6B:5E:04:B8:77:0F:2F:CE:74:DD:A6"
    register: login_response

  - name: add Test Host
    check_point_mgmt:
      command: add.host
      parameters:
        name: "test-123"
        ip-address: '1.1.1.1'
        color: "red"
      session-data: "{{login_response}}"
    ignore_errors: true

  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"
    ignore_errors: true
    register: publish_response

  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"
    ignore_errors: true
