---
- name: Check Point Tasks
  hosts: CPMgmtServer
  connection: httpapi
  collections:
    - check_point.mgmt

  tasks:
#    - name: task to have network
#      cp_mgmt_network:
#        name: "network1 name"
#        subnet: "22.1.76.0"
#        mask_length: 24

    - name: add-simple-gateway
      cp_mgmt_simple_gateway:
        ip_address: 192.0.2.1
        name: 
        state: present
        
    - name: Publish
      cp_mgmt_publish:
    
#  - name: "add simple-gateway"
#    check_point_mgmt:
#      command: add-simple-gateway
#      parameters:
#        name: "{{ gwArr.name }}"
#        #color "yellow"
#        ipv4-address: "{{ gwArr.eth0_ip }}"
#        version: "{{ gwArr.version }}"
#        one-time-password: "{{ gwArr.sic_pwd }}"
#        firewall: "true"
#        vpn: "true"
#        # application-control true
#        # url-filtering true
#        # ips true
#        # anti-bot true
#        # anti-virus true
#        # threat-emulation true
#        ### ###
#        interfaces:
#        - name: eth0
#          ipv4-address: "{{ gwArr.eth0_ip }}"
#          ipv4-network-mask: "{{ gwArr.eth0_netmask }}"
#          topology: "Internal"
#          anti-spoofing: "true"
#          topology-settings:
#            ip-address-behind-this-interface: "network defined by the interface ip and net mask"
#        - name: eth1
#          ipv4-address: "{{ gwArr.eth1_ip }}"
#          ipv4-network-mask: "{{ gwArr.eth1_netmask }}"
#          topology: "External"
#          anti-spoofing: "true"
#        - name: eth2
#          ipv4-address: "{{ gwArr.eth2_ip }}"
#          ipv4-network-mask: "{{ gwArr.eth2_netmask }}"
#          topology: Internal
#          anti-spoofing: "true"
#          topology-settings:
#            ip-address-behind-this-interface: "network defined by the interface ip and net mask"
#      session-data: "{{login_response}}"
#    register: add_gw_response
#    ignore_errors: true
    
