---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost 
  collections:
  - check_point.mgmt
  - check_point.gaia
  
  tasks:      
  - debug:
      msg: "{{ item.netIP }}"
    with_items: "{{ NetResult.query_result}}"
