---
- hosts: localhost
  gather_facts: False  
  collections:
  - check_point.mgmt
  - check_point.gaia
  
  tasks:      
  - debug:
      msg: "{{ item.netIP }}"
    with_items: "{{ NetResult.query_result}}"
