---
- name: Check Point Tasks
  hosts: CPMgmtServer
  connection: httpapi
  gather_facts: False
  collections:
    - check_point.mgmt

  tasks:
#    - name: task to have network
#      cp_mgmt_network:
#        name: "network1 name"
#        subnet: "22.1.76.0"
#        mask_length: 24

#    - name: add-simple-gateway
#      cp_mgmt_simple_gateway:
#        ip_address: {{item.baseIP1}}
#        name: {{item.nameFW1}}
#        state: present
#    - debug: 
#        msg: "{{item.baseIP1}}"
#      with_items: "{{FW1CmaSqlResults.query_result}}"

    - debug: 
        var: FW1CmaSqlResults
     
#    - name: set-simple-gateway
#      cp_mgmt_simple_gateway:
#        anti_bot: true
#        anti_virus: true
#        application_control: true
#        ips: true
#        name: test_gateway
#        threat_emulation: true
#        url_filtering: true
#        state: present
#        interfaces: 
#        - name: {{item.interface}}
#          ipv4-address: "{{ item.ipFW1 }}"
#          ipv4_mask_length: "{{ item.masklen }}"
#          topology: "Internal"
#          anti-spoofing: "true"
#          topology-settings:
#            ip-address-behind-this-interface: "network defined by the interface ip and net mask"
#        with_items: {{NetsqlResults.query_results}}
      
    - name: Publish
      cp_mgmt_publish:
    
#  - name: "add simple-gateway"
#    check_point_mgmt:
#      command: add-simple-gateway
#      parameters:
#        name: "{{ gwArr.name }}"
#        #color "yellow"
#        ipv4-address: "{{ gwArr.eth0_ip }}"
#        version: "{{ gwArr.version }}"
#        one-time-password: "{{ gwArr.sic_pwd }}"
#        firewall: "true"
#        vpn: "true"
#        # application-control true
#        # url-filtering true
#        # ips true
#        # anti-bot true
#        # anti-virus true
#        # threat-emulation true
#        ### ###
#        interfaces:
#        - name: eth0
#          ipv4-address: "{{ gwArr.eth0_ip }}"
#          ipv4-network-mask: "{{ gwArr.eth0_netmask }}"
#          topology: "Internal"
#          anti-spoofing: "true"
#          topology-settings:
#            ip-address-behind-this-interface: "network defined by the interface ip and net mask"
#        - name: eth1
#          ipv4-address: "{{ gwArr.eth1_ip }}"
#          ipv4-network-mask: "{{ gwArr.eth1_netmask }}"
#          topology: "External"
#          anti-spoofing: "true"
#        - name: eth2
#          ipv4-address: "{{ gwArr.eth2_ip }}"
#          ipv4-network-mask: "{{ gwArr.eth2_netmask }}"
#          topology: Internal
#          anti-spoofing: "true"
#          topology-settings:
#            ip-address-behind-this-interface: "network defined by the interface ip and net mask"
#      session-data: "{{login_response}}"
#    register: add_gw_response
#    ignore_errors: true
    
