---
- hosts: all
  gather_facts: False
  
  tasks:
  - name: get Location Network Info from DB
    mysql_query:
      login_db: fwinstall
      query: select ccn,locationNr,vlan,interface,physicalInt,description,netIP,vrrpIP,ipFW1,ipFW2,broadcastIP,masklen,dynObj,ipHelper1,ipHelper2,ipHelperCPPM1,ipHelperCPPM2,speed,duplex FROM net where locationNr="{{LocationNr}}"
    register: sqlResult
    
  - debug:
      msg: "{{ item.vlan }} is located in {{ item.interface }}"
    with_items: "{{ sqlResult.results }}"
