---
- hosts: all
  gather_facts: False  # don't gather facts against localhost
  tasks:
#  - name: Make sure pymysql is present
#    become: true # needed if the other tasks are not played as root
#    pip:
#      name: pymysql
#      state: present
      
#  - name: Set MySQL root Password
#    mysql_user:
#      login_user: "{{login_user}}"
#      login_password: "{{login_password}}"
#      name: 'root1'
#      password: "{{ User_passwd }}"
#      state: present

# profileID,lsmProfile,Gateway,primaryCmaName,primaryCmaIP,secondaryCmaName,secondaryCmaIP,logCmaName,logCmaIP

  - name: get_location Networks
    mysql_user:
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      name: 'root1'
      password: "{{ User_passwd }}"
      state: present
