---
- hosts: Mysql
  collections:
  - community.mysql
  - check_point.mgmt
  - check_point.gaia
  
  tasks:      
  - name: Get Data from Location Table
    mysql_query:
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select cty,ccn,locationNr,description,baseIP,baseIP1,lsmProfile,profileGroup,numberofFWs,nameFW1,nameFW2,nameCL from location where locationNr="{{LocationNr}}"
    register: LocationResult
    
  - name: stats Location Result
    set_stats:
      data:
        LocationSqlResults: "{{LocationResult}}"

  - name: Get Data from CMA Table for FW1
    mysql_query:
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select profileID,lsmProfile,Gateway,primaryCmaName,primaryCmaIP,secondaryCmaName,secondaryCmaIP,logCmaName,logCmaIP 
             from cma where Gateway='"{{item.nameFW1}}"'
    with_items: "{{LocationResult.query_result}}"
    register: Fw1CmaResult

  - name: stats Fw1
    set_stats:
      data:
        FW1CmaSqlResults: "{{Fw1CmaResult}}"

  - name: Get Data from CMA Table for FW2
    mysql_query:
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select profileID,lsmProfile,Gateway,primaryCmaName,primaryCmaIP,secondaryCmaName,secondaryCmaIP,logCmaName,logCmaIP 
             from cma where Gateway='"{{item.nameFW2}}"'
    with_items: "{{LocationResult.query_result}}"
    register: Fw2CmaResult

  - name: stats Fw2
    set_stats:
      data:
        FW2CmaSqlResults: "{{Fw2CmaResult}}"

  - name: Get Data from CMA Table for Cluster
    mysql_query:
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select profileID,lsmProfile,Gateway,primaryCmaName,primaryCmaIP,secondaryCmaName,secondaryCmaIP,logCmaName,logCmaIP 
             from cma where Gateway='"{{item.nameCL}}"'
    with_items: "{{LocationResult.query_result}}"
    register: ClusterCmaResult

  - name: stats Cluster
    set_stats:
      data:
        ClusterCmaSqlResults: "{{ClusterCmaResult}}"

  - name: Get Data from Net Table
    mysql_query:
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select ccn,locationNr,vlan,interface,physicalInt,description,netIP,vrrpIP,ipFW1,ipFW2,broadcastIP,masklen,dynObj,ipHelper1,ipHelper2,ipHelperCPPM1,ipHelperCPPM2,speed,duplex from net where locationNr="{{LocationNr}}"
    register: NetResult

  - name: stats Net SQL
    set_stats:
      data:
        NetsqlResults: "{{NetResult}}"

  - name: Get Data from Net Table
    mysql_query:
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select ccn,locationNr,ipNet,nextHop,description from routes where locationNr="{{LocationNr}}"
    register: RoutesResult

  - name: stats Routes
    set_stats:
      data:
        RoutesSqlResults: "{{RoutesResult}}"
        
  - debug:
      var: RoutesResult

  - debug:
      msg: "{{ item.nextHop }}"
	  with_items: "{{RoutesSqlResults.query_result}}"
    
