---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
#  gather_facts: False  # don't gather facts against localhost
  collections:
  - community.mysql
  - check_point.mgmt
  - check_point.gaia
  
  tasks:
  - name: Get Data from Location Table
    mysql_query:
      login_host: "{{MysqlServer}}"
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select cty,ccn,locationNr,description,MgmtIP,MgmtIPmask,lsmProfile,profileGroup,numberofFWs,nameFW,MemberID from location where (locationNr="{{LocationNr}}" and MemberID = {{MemberID}})
    register: LocationResult
    
  - name: Get Data from CMA Table
    mysql_query:
      login_host: "{{MysqlServer}}"
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select ccn,LocationNr,primaryCmaName,primaryCmaIP,secondaryCmaName,secondaryCmaIP,logCmaName,logCmaIP from cma where locationNr="{{LocationNr}}"
    register: CmaResult

#  - name: Get Data from Net Table
#    mysql_query:
#      login_host: "{{MysqlServer}}"
#      login_db: fwinstall
#      login_user: "{{login_user}}"
#      login_password: "{{login_password}}"
#      query: select ccn,locationNr,vlan,interface,physicalInt,description,netIP,member{{MemberID}} as FWIP,broadcastIP,masklen,dynObj,ipHelper1,ipHelper2,speed,duplex from net where locationNr="{{LocationNr}}"
#    register: NetResult

  - name: Get Data from Net Table
    mysql_query:
      login_host: "{{MysqlServer}}"
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select 
             location.cty,location.ccn,location.locationNr,location.description,location.MgmtIP,location.MgmtIPmask,location.lsmProfile,location.profileGroup,location.numberofFWs,location.nameFW,location.MemberID, 
             net.vlan as vlan,net.interface,net.interface_type,net.physicalInt,net.description,net.netIP,net.Member{{MemberID}} as FWIP,net.broadcastIP,net.masklen,net.dynObj,net.speed,net.duplex
             from location left JOIN net ON location.locationNr = net.LocationNr
             where (location.locationNr={{LocationNr}}) and (location.MemberID = {{MemberID}})
             order by net.vlan
    register: NetworkResult

  - name: Set stats
    set_stats:
      data:
        LocationSqlResults: "{{LocationResult}}"
        CmaSqlResults: "{{CmaResult}}"
#        NetsqlResults: "{{NetResult}}"
        NetworkSqlResults: "{{NetworkResult}}"
    
