---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
#  gather_facts: False  # don't gather facts against localhost
  collections:
  - community.mysql
  - check_point.mgmt
  - check_point.gaia
  
  tasks:
  - name: Get Data from Location Table
    mysql_query:
      login_host: "{{MysqlServer}}"
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select cty,ccn,locationNr,description,MgmtIP,MgmtIP-mask,lsmProfile,profileGroup,numberofFWs,nameFW,cluster from location where locationNr="{{LocationNr}}"
    register: LocationResult
    
  - name: Get Data from CMA Table
    mysql_query:
      login_host: "{{MysqlServer}}"
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select ccn,LocationNr,primaryCmaName,primaryCmaIP,secondaryCmaName,secondaryCmaIP,logCmaName,logCmaIP from cma where locationNr="{{LocationNr}}"
    register: CmaResult

  - name: Get Data from Net Table
    mysql_query:
      login_host: "{{MysqlServer}}"
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select ccn,locationNr,vlan,interface,physicalInt,description,netIP,vrrpIP,ipFW1,ipFW2,broadcastIP,masklen,dynObj,ipHelper1,ipHelper2,ipHelperCPPM1,ipHelperCPPM2,speed,duplex from net where locationNr="{{LocationNr}}"
    register: NetResult

  - name: Get Data from Net Table
    mysql_query:
      login_host: "{{MysqlServer}}"
      login_db: fwinstall
      login_user: "{{login_user}}"
      login_password: "{{login_password}}"
      query: select ccn,locationNr,ipNet,nextHop,description from routes where locationNr="{{LocationNr}}"
    register: RoutesResult

  - name: Set stats
    set_stats:
      data:
        LocationSqlResults: "{{LocationResult}}"
        CmaSqlResults: "{{CmaResult}}"
        NetsqlResults: "{{NetResult}}"
        RoutesSqlResults: "{{RoutesResult}}"
    
