---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  tasks:
  - name: Set MySQL root Password
    mysql_user:
      login_host: 'localhost'
      login_user: 'adminer'
      login_password: 'Kamilletee1'
      name: 'root1'
      password: '{{ mysql_pass }}'
      state: present
