---
- name: Check Point Tasks
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - json_body: {
               'user': {{mgmt_user}},
               'password': {{mgmt_password}}
               }
  tasks:
    - name: Set stats
      set_fact: 
        URLstart: "https://{{mgmt_server}}/web_api"

    - name: Set stats
      set_fact: 
        FWName: "{{item.nameFW}}"
      with_items: "{{LocationSqlResults.query_result}}"  
    
    - name: Set stats
      set_fact: 
        MgmtIP: "{{item.MgmtIP}}"
      with_items: "{{LocationSqlResults.query_result}}"

    - name: login to Server
      uri:
        method: post
        url: "{{URLstart}}/login"
        validate_certs: no
        return_content: yes
        body_format: json
        headers:
          Accept: application/json
        body: "{{json_body}}"
      register: login_response

    - name: Set stats sid
      set_fact:
        sid: "{{item}}"
      with_items: "{{ login_response.json.sid}}"
      
    - name: add-simple-gateway
      cp_mgmt_simple_gateway:
        ip_address: "{{MgmtIP}}"
        name: "{{FWName}}"
        state: present
          
    - name: set-simple-gateway
      cp_mgmt_simple_gateway:
        anti_bot: true
        anti_virus: true
        application_control: true
        ips: true
        name: "{{FWName}}"
        threat_emulation: true
        url_filtering: true
        state: present
        interfaces: 
        - name: "{{item.interface}}"
          ipv4-address: "{{ item.FWIP }}"
          ipv4_mask_length: "{{ item.masklen }}"
          topology: "Internal"
          anti-spoofing: "true"
          topology-settings:
            ip-address-behind-this-interface: "network defined by the interface ip and net mask"
          with_items: "{{NetsqlResults.query_result |to_json}}"
          when: 
            - item.FWIP != None 

    - name: Publish changes
      uri:
        method: post
        url: "{{URLstart}}/publish"
        validate_certs: no
        return_content: yes
        body_format: json
        headers:
          Accept: application/json
          x-chkp-sid : "{{sid}}"
        body: {}
    
    - name: logout to Server
      uri:
        method: post
        url: "{{URLstart}}/logout"
        validate_certs: no
        return_content: yes
        body_format: json
        headers:
          Accept: application/json
          x-chkp-sid : "{{sid}}"
        body: {}
