---
- name: Check Point Tasks
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Set stats
      set_fact: 
        URLstart: "https://{{mgmt_server}}/web_api"

    - name: Set stats
      set_fact: 
        FWName: "{{item.nameFW}}"
      with_items: "{{LocationSqlResults.query_result}}"  
    
    - name: Set stats
      set_fact: 
        MgmtIP: "{{item.MgmtIP}}"
      with_items: "{{LocationSqlResults.query_result}}"

#    - name: login to Server
#      uri:
#        method: post
#        url: "{{URLstart}}/login"
#        validate_certs: no
#        return_content: yes
#        body_format: json
#        headers:
#          Accept: application/json
#        body: {
#               'user': "{{mgmt_username}}",
#               'password': "{{mgmt_password}}"
#               }
#      register: login_response

#    - name: Set stats sid
#      set_fact:
#        sid: "{{item}}"
#      with_items: "{{ login_response.json.sid}}"
      
#    - name: add-simple-gateway
#      uri:
#        method: post
#        url: "{{URLstart}}/add-simple-gateway"
#        validate_certs: no
#        return_content: yes
#        body_format: json
#        headers:
#          Accept: application/json
#          x-chkp-sid : "{{sid}}"
#        body: {
#                 'name' : "{{FWName}}",
#                 'ip-address' : "{{MgmtIP}}"
#              }
      
    - name: Initiate User List
      set_fact:
        interf: []
       
       
    - debug:
        msg: "#### {{item.interface}}#### {{item.interface_type}}#### {{item.FWIP}}#### {{item.masklen}}"
      with_items: "{{NetworkSqlResults.query_result}}"
      when:
        - item.FWIP != None
    
#    - name: Add new JSON Objects to List
#      set_fact:
#        interf: "{{ interf + [{
#                               'name': item.interface,
#                               'interface-type' : item.interface_type,
#                               'ipv4-address':  item.FWIP,
#                               'ipv4-mask_length': item.masklen,
#                               'topology': 'Internal',
#                               'anti_spoofing': 'true',
#                               'anti-spoofing-settings' : {
#                                                            'action' : 'prevent'
#                                                          }
#                               'topology_settings': {
#                                                      'ip_address_behind_this_interface': 'network defined by the interface ip and net mask'
#                                                    }
#                              }]
#                 }}"
#      with_items: "{{NetworkSqlResults.query_result}}"
#      when:
#        - item.FWIP != None
        
#    - name: add-simple-gateway
#      uri:
#        method: post
#        url: "{{URLstart}}/add-simple-gateway"
#        validate_certs: no
#        return_content: yes
#        body_format: json
#        headers:
#          Accept: application/json
#          x-chkp-sid : "{{sid}}"
#        body: {
#                'name': "{{FWName}}",
#                'anti_bot': true,
#                'anti_virus': true,
#                'application_control': true,
#                'ips': true,        
#                'threat_emulation': true,
#                'url_filtering': true,
#                'interfaces': "{{interf | to_json}}"
#               }
               
#    - name: Publish changes
#      uri:
#        method: post
#        url: "{{URLstart}}/publish"
#        validate_certs: no
#        return_content: yes
#        body_format: json
#        headers:
#          Accept: application/json
#          x-chkp-sid : "{{sid}}"
#        body: {}
    
#    - name: logout to Server
#      uri:
#        method: post
#        url: "{{URLstart}}/logout"
#        validate_certs: no
#        return_content: yes
#        body_format: json
#        headers:
#          Accept: application/json
#          x-chkp-sid : "{{sid}}"
#        body: {}
